/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_spi.h"
#include "fsl_flexspi.h"
#include "fsl_clock.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_i2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for FLEXCOMM0 */
/* Definition of peripheral ID */
#define FLEXCOMM0_EEG_SPI_PERIPHERAL ((SPI_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM0_EEG_SPI_CLOCK_SOURCE 16000000UL
/* Definition of peripheral ID */
#define FLEXSPI_PERIPHERAL FLEXSPI
/* Size of LUT (Look-up Table) */
#define FLEXSPI_LUT_LENGTH 64
/* FLEXSPI interrupt vector ID (number). */
#define FLEXSPI_IRQN FLEXSPI_IRQn
/* FLEXSPI interrupt handler identifier. */
#define FLEXSPI_IRQHANDLER FLEXSPI_IRQHandler
/* Definition of peripheral ID */
#define FLEXCOMM1_BLE_UART_PERIPHERAL ((USART_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define FLEXCOMM1_BLE_UART_CLOCK_SOURCE 16000000UL
/* BOARD_InitPeripherals defines for FLEXCOMM2 */
/* Definition of peripheral ID */
#define FLEXCOMM2_BATT_I2C_PERIPHERAL ((I2C_Type *)FLEXCOMM2)
/* Definition of the clock source frequency */
#define FLEXCOMM2_BATT_I2C_CLOCK_SOURCE 16000000UL
/* BOARD_InitPeripherals defines for FLEXCOMM3 */
/* Definition of peripheral ID */
#define FLEXCOMM3_SENSOR_I2C_PERIPHERAL ((I2C_Type *)FLEXCOMM3)
/* Definition of the clock source frequency */
#define FLEXCOMM3_SENSOR_I2C_CLOCK_SOURCE 16000000UL
/* Definition of peripheral ID */
#define FLEXCOMM5_DEBUG_UART_PERIPHERAL ((USART_Type *)FLEXCOMM5)
/* Definition of the clock source frequency */
#define FLEXCOMM5_DEBUG_UART_CLOCK_SOURCE 16000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const spi_master_config_t FLEXCOMM0_EEG_SPI_config;
extern const flexspi_config_t FLEXSPI_config;
extern const uint32_t FLEXSPI_LUT[FLEXSPI_LUT_LENGTH];
extern const usart_config_t FLEXCOMM1_BLE_UART_config;
extern const i2c_master_config_t FLEXCOMM2_BATT_I2C_config;
extern const i2c_master_config_t FLEXCOMM3_SENSOR_I2C_config;
extern const usart_config_t FLEXCOMM5_DEBUG_UART_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
