/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_ANAMUX_EN 0x0200u      /*!<@brief Analog mux is enabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_FUNC3 0x03u            /*!<@brief Selects pin function 3 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_SCK (coord G1), EEG_SCLK
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_SCLK_PERIPHERAL FLEXCOMM0 /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_SCLK_SIGNAL SCK           /*!<@brief Signal name */
                                                     /* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), EEG_MISO
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_MISO_PERIPHERAL FLEXCOMM0         /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_MISO_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                             /* @} */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), EEG_MOSI
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_MOSI_PERIPHERAL FLEXCOMM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_MOSI_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                               /* @} */

/*! @name FC0_CTS_SDA_SSEL0 (coord H2), EEG_CSn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_CSn_PERIPHERAL FLEXCOMM0       /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_CSn_SIGNAL CTS_SDA_SSEL0       /*!<@brief Signal name */
                                                          /* @} */

/*! @name PIO0_4 (coord J1), EEG_START
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_START_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_START_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_EEG_START_CHANNEL 4                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EEG_START_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EEG_START_GPIO_PIN_MASK (1U << 4U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_EEG_START_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EEG_START_PIN 4U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_EEG_START_PIN_MASK (1U << 4U)                /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PIO0_5 (coord F4), EEG_RESETn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_RESETn_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_RESETn_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_EEG_RESETn_CHANNEL 5                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EEG_RESETn_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EEG_RESETn_GPIO_PIN_MASK (1U << 5U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_EEG_RESETn_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EEG_RESETn_PIN 5U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_EEG_RESETn_PIN_MASK (1U << 5U)                /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PIO0_7 (coord J2), EEG_PWDNn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_PWDNn_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_PWDNn_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_EEG_PWDNn_CHANNEL 7                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EEG_PWDNn_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EEG_PWDNn_GPIO_PIN_MASK (1U << 7U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_EEG_PWDNn_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EEG_PWDNn_PIN 7U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_EEG_PWDNn_PIN_MASK (1U << 7U)                /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PIO0_13 (coord G3), EEG_DRDYn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_DRDYn_PERIPHERAL GPIO                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_DRDYn_SIGNAL PIO0                       /*!<@brief Signal name */
#define BOARD_INITPINS_EEG_DRDYn_CHANNEL 13                        /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EEG_DRDYn_GPIO GPIO                         /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EEG_DRDYn_GPIO_PIN_MASK (1U << 13U)         /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_EEG_DRDYn_PORT 0U                           /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EEG_DRDYn_PIN 13U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_EEG_DRDYn_PIN_MASK (1U << 13U)              /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PIO2_7 (coord U16), EEG_LDO_EN
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_EEG_LDO_EN_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_EEG_LDO_EN_SIGNAL PIO2                        /*!<@brief Signal name */
#define BOARD_INITPINS_EEG_LDO_EN_CHANNEL 7                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EEG_LDO_EN_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EEG_LDO_EN_GPIO_PIN_MASK (1U << 7U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_EEG_LDO_EN_PORT 2U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EEG_LDO_EN_PIN 7U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_EEG_LDO_EN_PIN_MASK (1U << 7U)                /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name FC1_TXD_SCL_MISO_WS (coord K4), BT_UART_TXD
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_TXD_PERIPHERAL FLEXCOMM1         /*!<@brief Peripheral name */
#define BOARD_INITPINS_BT_UART_TXD_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                                /* @} */

/*! @name FC1_RXD_SDA_MOSI_DATA (coord L3), BT_UART_RXD
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_RXD_PERIPHERAL FLEXCOMM1           /*!<@brief Peripheral name */
#define BOARD_INITPINS_BT_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                  /* @} */

/*! @name FC1_CTS_SDA_SSEL0 (coord J3), BT_UART_CTSn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_CTSn_PERIPHERAL FLEXCOMM1       /*!<@brief Peripheral name */
#define BOARD_INITPINS_BT_UART_CTSn_SIGNAL CTS_SDA_SSEL0       /*!<@brief Signal name */
                                                               /* @} */

/*! @name FC1_RTS_SCL_SSEL1 (coord L1), BT_UART_RTSn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_RTSn_PERIPHERAL FLEXCOMM1       /*!<@brief Peripheral name */
#define BOARD_INITPINS_BT_UART_RTSn_SIGNAL RTS_SCL_SSEL1       /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI0A_SCLK (coord T9), NAND_SCK
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_SCK_PERIPHERAL FLEXSPI      /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_SCK_SIGNAL FLEXSPI_A_SCLK   /*!<@brief Signal name */
                                                        /* @} */

/*! @name FLEXSPI0A_SS0_N (coord T4), NAND_CSn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_CSn_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_CSn_SIGNAL FLEXSPI_A_SS0_B   /*!<@brief Signal name */
                                                         /* @} */

/*! @name FLEXSPI0A_DATA0 (coord T5), NAND_D0
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_D0_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_D0_SIGNAL FLEXSPI_A_DATA0   /*!<@brief Signal name */
                                                        /* @} */

/*! @name FLEXSPI0A_DATA1 (coord U5), NAND_D1
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_D1_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_D1_SIGNAL FLEXSPI_A_DATA1   /*!<@brief Signal name */
                                                        /* @} */

/*! @name FLEXSPI0A_DATA2 (coord P6), NAND_D2
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_D2_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_D2_SIGNAL FLEXSPI_A_DATA2   /*!<@brief Signal name */
                                                        /* @} */

/*! @name FLEXSPI0A_DATA3 (coord P7), NAND_D3
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_NAND_D3_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPINS_NAND_D3_SIGNAL FLEXSPI_A_DATA3   /*!<@brief Signal name */
                                                        /* @} */

/*! @name FC2_CTS_SDA_SSEL0 (coord D7), I2C5_SDA
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SDA_PERIPHERAL FLEXCOMM2       /*!<@brief Peripheral name */
#define BOARD_INITPINS_I2C5_SDA_SIGNAL CTS_SDA_SSEL0       /*!<@brief Signal name */
                                                           /* @} */

/*! @name FC2_RTS_SCL_SSEL1 (coord B7), I2C5_SCL
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SCL_PERIPHERAL FLEXCOMM2       /*!<@brief Peripheral name */
#define BOARD_INITPINS_I2C5_SCL_SIGNAL RTS_SCL_SSEL1       /*!<@brief Signal name */
                                                           /* @} */

/*! @name FC3_CTS_SDA_SSEL0 (coord B9), I2C6_SDA
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SDA_PERIPHERAL FLEXCOMM3       /*!<@brief Peripheral name */
#define BOARD_INITPINS_I2C6_SDA_SIGNAL CTS_SDA_SSEL0       /*!<@brief Signal name */
                                                           /* @} */

/*! @name FC3_RTS_SCL_SSEL1 (coord A9), I2C6_SCL
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SCL_PERIPHERAL FLEXCOMM3       /*!<@brief Peripheral name */
#define BOARD_INITPINS_I2C6_SCL_SIGNAL RTS_SCL_SSEL1       /*!<@brief Signal name */
                                                           /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
