/*
 * eeg_constants.h
 *
 *  Created on: Sep 3, 2021
 *      Author: DavidWang
 */

#ifndef EEG_READER_EEG_CONSTANTS_H_
#define EEG_READER_EEG_CONSTANTS_H_

#include "config.h"

#if defined(VARIANT_FF2)
#define ADS_GAIN_DEFAULT 12
#define EEG_PREAMP_GAIN 200
#define EEG_TOTAL_GAIN (ADS_GAIN_DEFAULT*EEG_PREAMP_GAIN)
#define EEG_ADC2VOLTS_NUMERATOR (4.0/(8388608.0-1))
#define EEG_SCALAR_V (EEG_ADC2VOLTS_NUMERATOR/EEG_TOTAL_GAIN)
#define EEG_SCALAR_UV (1000000.0*EEG_SCALAR_V)
#elif defined(VARIANT_FF3)
#define ADS_GAIN_DEFAULT 12
#define EEG_PREAMP_GAIN 10
#define EEG_TOTAL_GAIN (ADS_GAIN_DEFAULT*EEG_PREAMP_GAIN)
#define EEG_ADC2VOLTS_NUMERATOR (4.0/(8388608.0-1))
#define EEG_SCALAR_V (EEG_ADC2VOLTS_NUMERATOR/EEG_TOTAL_GAIN)
#define EEG_SCALAR_UV (1000000.0*EEG_SCALAR_V)
#endif

#endif /* EEG_READER_EEG_CONSTANTS_H_ */
