/* Generated by version.mk. Do not edit. */
#pragma once
#define FW_VERSION_MAJOR      0
#define FW_VERSION_MINOR      9
#define FW_VERSION_STRING     "v0.9d"
#define FW_VERSION_INTEGER    ((FW_VERSION_MAJOR<<16)|(FW_VERSION_MINOR))
#define FW_VERSION_GIT_STRING FW_VERSION_STRING "-" "v0.9-127-geed1206+"
